// lumen command line driver.
//
//   lumen script.lum          run a file
//   lumen                     REPL
//   lumen --dump script.lum   print the generated bytecode
//
// The flags exist because the interesting part of this project is the
// pipeline, and a compiler you cannot look inside is a compiler you cannot
// debug.

#include <cstring>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>

#include "lumen/lumen.hpp"

namespace {

void usage() {
  std::cerr <<
      "usage: lumen [options] [script]\n"
      "\n"
      "  --dump             print the generated bytecode and exit\n"
      "  --no-optimize      skip AST constant folding and dead code removal\n"
      "  --no-peephole      skip bytecode superinstructions\n"
      "  --stress-gc        run a collection on every allocation\n"
      "  --stats            report optimizer, compiler and VM counters\n"
      "  -h, --help         show this message\n";
}

int report(const lumen::RunResult& result, bool stats) {
  for (const auto& e : result.errors) {
    std::cerr << "error: " << e.format() << "\n";
  }
  if (!result.runtime_error.empty()) {
    std::cerr << "runtime error: " << result.runtime_error << "\n";
  }
  if (stats) {
    std::cerr << "\n-- optimizer --\n"
              << "  constants folded        " << result.optimizer.constants_folded << "\n"
              << "  branches eliminated     " << result.optimizer.branches_eliminated << "\n"
              << "  statements removed      " << result.optimizer.statements_removed << "\n"
              << "  algebraic rewrites      " << result.optimizer.algebraic_simplifications << "\n"
              << "-- compiler --\n"
              << "  functions compiled      " << result.compiler.functions_compiled << "\n"
              << "  peephole rewrites       " << result.compiler.peephole_rewrites << "\n"
              << "-- vm --\n"
              << "  instructions executed   " << result.vm.instructions << "\n"
              << "  calls                   " << result.vm.calls << "\n"
              << "  max stack depth         " << result.vm.max_stack_depth << "\n"
              << "  max frame depth         " << result.vm.max_frame_depth << "\n";
  }
  if (!result.errors.empty()) return 65;
  if (!result.runtime_error.empty()) return 70;
  return 0;
}

int run_file(const std::string& path, lumen::RunOptions options, bool stats) {
  std::ifstream file(path, std::ios::binary);
  if (!file) {
    std::cerr << "error: cannot open '" << path << "'\n";
    return 66;
  }
  std::ostringstream buffer;
  buffer << file.rdbuf();
  const std::string source = buffer.str();

  lumen::RunResult result = lumen::run_source(source, std::cout, options);
  if (options.dump_bytecode && result.errors.empty()) {
    std::cout << result.disassembly;
    return 0;
  }
  return report(result, stats);
}

int repl(lumen::RunOptions options, bool stats) {
  std::cout << "lumen repl. ctrl-d to exit.\n";
  std::string line;
  for (;;) {
    std::cout << "> " << std::flush;
    if (!std::getline(std::cin, line)) {
      std::cout << "\n";
      return 0;
    }
    if (line.empty()) continue;
    // Each line is its own program. Persisting globals between lines would
    // mean keeping one VM alive, which is a worthwhile extension but changes
    // the ownership of the heap; it is deliberately not faked here.
    lumen::RunResult result = lumen::run_source(line, std::cout, options);
    if (options.dump_bytecode && result.errors.empty()) {
      std::cout << result.disassembly;
      continue;
    }
    report(result, stats);
  }
}

}  // namespace

int main(int argc, char** argv) {
  lumen::RunOptions options;
  bool stats = false;
  std::string script;

  for (int i = 1; i < argc; ++i) {
    const std::string arg = argv[i];
    if (arg == "--dump") {
      options.dump_bytecode = true;
    } else if (arg == "--no-optimize") {
      options.optimize = false;
    } else if (arg == "--no-peephole") {
      options.peephole = false;
    } else if (arg == "--stress-gc") {
      options.stress_gc = true;
    } else if (arg == "--stats") {
      stats = true;
      options.count_instructions = true;
    } else if (arg == "-h" || arg == "--help") {
      usage();
      return 0;
    } else if (!arg.empty() && arg[0] == '-') {
      std::cerr << "error: unknown option '" << arg << "'\n";
      usage();
      return 64;
    } else if (script.empty()) {
      script = arg;
    } else {
      std::cerr << "error: more than one script given\n";
      return 64;
    }
  }

  return script.empty() ? repl(options, stats) : run_file(script, options, stats);
}
